name: Split Text File

on:
  push:
    branches:
      - main

jobs:
  split-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run split script
      run: python split.py
